-d C:\Users\gabis\Desktop\UJA\PPHH\knight_rider\impl\gwsynthesis\knight_rider.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\gabis\Desktop\UJA\PPHH\knight_rider\src\top.cst
-cfg C:\Users\gabis\Desktop\UJA\PPHH\knight_rider\impl\pnr\device.cfg
-sdc C:\Users\gabis\Desktop\UJA\PPHH\knight_rider\src\timing.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
